#baseurl = "http://rainbowsixbootcamp.com"
baseurl = "http://localhost:1313"

theme = 'gaming-theme'

languageCode = "en-us"
title = "Rainbow Six Bootcamp"

[taxonomies]
  post = "/:year/:month/:slug/"
  tag = "tags"
  operator = "operators"
  cartridge = "cartridges"
  manufacturer ="manufacturers"
  class ="classes"

[params]
  image = "/images/hqdefault.jpg"
  disqusShortname = "rainbowsixbootcamp"
  CopyExtra = "Rainbow Six Bootcamp was created using content and materials from Rainbow Six: Siege © Ubisoft Entertainment or its licensors."

[params.relatedArticles]
  excludedTags = ["operator","gadget","weapon","ctu"]

[params.adsense]
  client = "ca-pub-0574310089910343"
  footerAd = "7682239174"
  sidebarAd = "4318473570"

[[params.socialLinks]]
  key = "facebook"
  link = "https://www.facebook.com/rainbowsixbootcamp/"

[[params.socialLinks]]
  key = "github"
  link = "https://github.com/christophermancini/rainbow-six-bootcamp"

[[params.socialLinks]]
  key = "google-plus"
  link = "https://plus.google.com/102116020583969691630"

[[params.socialLinks]]
  key = "twitter"
  link = "https://twitter.com/R6_Bootcamp"

[[params.socialLinks]]
  key = "youtube"
  link = "https://www.youtube.com/channel/UCXQEfUKsCBMwccbUeQjYMoQ"

[params.operatorRel.ash]
  title = "Ash"
  src = "/advanced-training/operator/fbi-swat/ash/"

[params.operatorRel.castle]
  title = "Castle"
  src = "/advanced-training/operator/fbi-swat/castle/"

[params.operatorRel.pulse]
  title = "Pulse"
  src = "/advanced-training/operator/fbi-swat/pulse/"

[params.operatorRel.thermite]
  title = "Thermite"
  src = "/advanced-training/operator/fbi-swat/thermite/"

[params.operatorRel.doc]
  title = "Doc"
  src = "/advanced-training/operator/gign/doc/"

[params.operatorRel.montagne]
  title = "Montagne"
  src = "/advanced-training/operator/gign/montagne/"

[params.operatorRel.rook]
  title = "Rook"
  src = "/advanced-training/operator/gign/rook/"

[params.operatorRel.twitch]
  title = "Twitch"
  src = "/advanced-training/operator/gign/twitch/"

[params.operatorRel.bandit]
  title = "Bandit"
  src = "/advanced-training/operator/gsg-9/bandit/"

[params.operatorRel.blitz]
  title = "Blitz"
  src = "/advanced-training/operator/gsg-9/blitz/"

[params.operatorRel.iq]
  title = "IQ"
  src = "/advanced-training/operator/gsg-9/iq/"

[params.operatorRel.jager]
  title = "Jäger"
  src = "/advanced-training/operator/gsg-9/jager/"

[params.operatorRel.mute]
  title = "Mute"
  src = "/advanced-training/operator/sas/mute/"

[params.operatorRel.sledge]
  title = "Sledge"
  src = "/advanced-training/operator/sas/sledge/"

[params.operatorRel.smoke]
  title = "Smoke"
  src = "/advanced-training/operator/sas/smoke/"

[params.operatorRel.thatcher]
  title = "Thatcher"
  src = "/advanced-training/operator/sas/thatcher/"

[params.operatorRel.fuze]
  title = "Fuze"
  src = "/advanced-training/operator/spetsnaz/fuze/"

[params.operatorRel.glaz]
  title = "Glaz"
  src = "/advanced-training/operator/spetsnaz/glaz/"

[params.operatorRel.kapkan]
  title = "Kapkan"
  src = "/advanced-training/operator/spetsnaz/kapkan/"

[params.operatorRel.tachanka]
  title = "Tachanka"
  src = "/advanced-training/operator/spetsnaz/tachanka.md"

[[menu.main]]
  name = "HOME"
  identifier = "home"
  url = "/"
  weight = 0

[[menu.main]]
  name = "Basic Training"
  identifier = "basic-training"
  url = "/basic-training/"
  weight = 1

[[menu.main]]
  name = "Advanced Training"
  identifier = "advanced-training"
  url = "/advanced-training/"
  weight = 2

[[menu.main]]
  name = "Maps"
  identifier = "maps"
  parent = "advanced-training"
  url = "/tags/map"

[[menu.main]]
  name = "Sitations"
  identifier = "situations"
  parent = "advanced-training"
  url = "/tags/situation"

[[menu.main]]
  name = "Primary Weapons"
  identifier = "primary-weapons"
  parent = "gear"
  url = "/tags/primary weapon"

[[menu.main]]
  name = "Secondary Weapons"
  identifier = "secondary-weapons"
  parent = "gear"
  url = "/tags/secondary weapon"

[[menu.main]]
  name = "Gadgets"
  identifier = "gadgets"
  parent = "gear"
  url = "/tags/gadget"

[[menu.main]]
  name = "Community"
  identifier = "community"
  url = "/community/"
  weight = 3
