#baseurl = "http://rainbowsixbootcamp.com"
baseurl = "http://localhost:1313"

theme = 'gaming-theme'

languageCode = "en-us"
title = "Rainbow Six Bootcamp"

[taxonomies]
  post = "/:year/:month/:slug/"
  tag = "tags"
  operator = "operators"

[params]
  image = "/images/hqdefault.jpg"
  disqusShortname = "rainbowsixbootcamp"
  CopyExtra = "Rainbow Six Bootcamp was created using content and materials from Rainbow Six: Siege © Ubisoft Entertainment or its licensors."

[params.relatedArticles]
  excludedTags = ["operator","gadget","weapon","ctu"]

[params.adsense]
  client = "ca-pub-0574310089910343"
  footerAd = "7682239174"
  sidebarAd = "4318473570"

[[params.socialLinks]]
  key = "facebook"
  link = "https://www.facebook.com/rainbowsixbootcamp/"

[[params.socialLinks]]
  key = "github"
  link = "https://github.com/christophermancini/rainbow-six-bootcamp"

[[params.socialLinks]]
  key = "google-plus"
  link = "https://plus.google.com/102116020583969691630"

[[params.socialLinks]]
  key = "twitter"
  link = "https://twitter.com/R6_Bootcamp"

[[params.socialLinks]]
  key = "youtube"
  link = "https://www.youtube.com/channel/UCXQEfUKsCBMwccbUeQjYMoQ"

[[menu.main]]
  name = "HOME"
  identifier = "home"
  url = "/"
  weight = 0

[[menu.main]]
  name = "Basic Training"
  identifier = "basic-training"
  url = "/basic-training/"
  weight = 1

[[menu.main]]
  name = "Advanced Training"
  identifier = "advanced-training"
  url = "/advanced-training/"
  weight = 2

[[menu.main]]
  name = "Maps"
  identifier = "maps"
  parent = "advanced-training"
  url = "/tags/map"

[[menu.main]]
  name = "Sitations"
  identifier = "situations"
  parent = "advanced-training"
  url = "/tags/situation"

[[menu.main]]
  name = "Primary Weapons"
  identifier = "primary-weapons"
  parent = "gear"
  url = "/tags/primary weapon"

[[menu.main]]
  name = "Secondary Weapons"
  identifier = "secondary-weapons"
  parent = "gear"
  url = "/tags/secondary weapon"

[[menu.main]]
  name = "Gadgets"
  identifier = "gadgets"
  parent = "gear"
  url = "/tags/gadget"

[[menu.main]]
  name = "Community"
  identifier = "community"
  url = "/community/"
  weight = 3
