#baseurl = "http://rainbowsixbootcamp.com"
baseurl = "http://localhost:1313"

theme = 'gaming-theme'

languageCode = "en-us"
title = "Rainbow Six Bootcamp"

preserveTaxonomyNames = true

[taxonomies]
  tag = "tags"
  operator = "operators"
  cartridge = "cartridges"
  manufacturer = "manufacturers"
  class = "classes"
  mod-type = "mod-types"

[params]
  image = "/images/hqdefault.jpg"
  disqusShortname = "rainbowsixbootcamp"
  CopyExtra = "Rainbow Six Bootcamp was created using content and materials from Rainbow Six: Siege © Ubisoft Entertainment or its licensors."
  siegeSections = ["advanced-training","basic-training"]

[params.services]
  eagerSite = "Q2mnQ6g7ja"
  googleAnalytics = "UA-4220075-8"

[params.relatedArticles]
  excludedTags = ["operator","gadget","weapon","ctu"]

[params.adsense]
  client = "ca-pub-0574310089910343"
  footerAd = "7682239174"
  contentAd1 = "4318473570"
  contentAd2 = "1972804778"

[[params.socialLinks]]
  key = "facebook"
  link = "https://www.facebook.com/rainbowsixbootcamp/"

[[params.socialLinks]]
  key = "github"
  link = "https://github.com/christophermancini/rainbow-six-bootcamp"

[[params.socialLinks]]
  key = "google-plus"
  link = "https://plus.google.com/102116020583969691630"

[[params.socialLinks]]
  key = "twitter"
  link = "https://twitter.com/R6_Bootcamp"

[[params.socialLinks]]
  key = "youtube"
  link = "https://www.youtube.com/channel/UCXQEfUKsCBMwccbUeQjYMoQ"

[[menu.main]]
  name = "Basics"
  identifier = "basic-training"
  url = "/basic-training/"
  weight = 1

[[menu.main]]
  name = "Advanced"
  identifier = "advanced-training"
  url = "/advanced-training/"
  weight = 2

[[menu.main]]
  name = "Maps"
  identifier = "maps"
  parent = "advanced-training"
  url = "/tags/map"

[[menu.main]]
  name = "Situations"
  identifier = "situations"
  parent = "advanced-training"
  url = "/tags/situation"

[[menu.main]]
  name = "Community"
  identifier = "community"
  url = "/community/"
  weight = 3
